# Generated by Django 3.2 on 2024-04-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo',
            new_name='title',
        ),
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
